{
 "title": "EDEN",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Block delay (cdfOne)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfOne",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load average (5 min)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Block Height (absolute)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peers Connected (BP)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peers_connectedPeers_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing connections (P2P)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_outgoingConns{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Incoming connections (P2P)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_incomingConns{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cardano Last Block Slot Height",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Remaining KES Periods",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-cardano_node_metrics_nodeStartTime_int)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "bargauge",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 12, "w": 4, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SWAP Usage",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cardano_node_metrics_epoch_int", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Time Synchronisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_timex_maxerror_seconds * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks Assigned",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_nodeIsLeaderNum_int",
     "legendFormat": "{{instance}} Assigned"
    }
   ]
  },
  {
   "title": "CPU Utilization (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Height (absolute)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks Forged",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blocksForgedNum_int",
     "legendFormat": "{{instance}} forged"
    }
   ]
  },
  {
   "title": "Missed slots",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotsMissedNum_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slot length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Historic memory usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks Adopted",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_adopted_int",
     "legendFormat": "{{instance}} adopted"
    }
   ]
  },
  {
   "title": "Cardano Chain Density",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_density_real * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cardano_node_ChainDB_metrics_blockNum_int[150s])*60",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(cardano_node_metrics_blockNum_int[150s])*60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks Discarded",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_didnt_adopt_int",
     "legendFormat": "{{instance}} discarded"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}